name: release docs CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Checkout -> Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Process NPM
        run: |
          npm install
          npm run docs:build
        env:
          CI: true

      - name: Deploy
        env:
          ACCESS_TOKEN_DEPLOY: ${{secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/.vuepress/dist
        uses: veaba/vuepress-actions@v0.83 
